/*
 * SetupProxyDialog.java
 *
 * Created on 29. November 2007, 18:32
 */
package acdsee.gui.dialogs;

import java.awt.Component;

import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

import acdsee.io.http.ProxySettings;

/**
 *
 * @author A752203
 */
public class SetupProxyDialog extends javax.swing.JDialog {

    /**
     * Creates new form SetupProxyDialog
     */
    public SetupProxyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonHelp = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rb_directConnection = new javax.swing.JRadioButton();
        rb_manuallySetConnectionDetails = new javax.swing.JRadioButton();
        rb_connectionDetection = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        httpProxyPort = new javax.swing.JTextField();
        httpProxyLabel = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        httpProxyPortLabel = new javax.swing.JLabel();
        httpProxyURL = new javax.swing.JTextField();
        cb_useSameProxyForAllProtocols = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sslProxyLabel = new javax.swing.JLabel();
        sslProxyURL = new javax.swing.JTextField();
        sslProxyPortLabel = new javax.swing.JLabel();
        sslProxyPort = new javax.swing.JTextField();
        ftpProxyPort = new javax.swing.JTextField();
        gopherProxyPort = new javax.swing.JTextField();
        socksHostPort = new javax.swing.JTextField();
        socksPortLabel = new javax.swing.JLabel();
        ftpProxyPortLabel = new javax.swing.JLabel();
        gopherProxyURL = new javax.swing.JTextField();
        ftpProxyURL = new javax.swing.JTextField();
        socksHostURL = new javax.swing.JTextField();
        socksHostLabel = new javax.swing.JLabel();
        gopherProxyLabel = new javax.swing.JLabel();
        ftpProxyLabel = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        gopherProxyPortLabel = new javax.swing.JLabel();
        rb_proxyConfigurationViaURL = new javax.swing.JRadioButton();
        tf_autoProxyConfigurationURL = new javax.swing.JTextField();
        buttonReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verbindungs-Einstellungen");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setResizable(false);

        buttonHelp.setText("Help");

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proxies für den Zugriff auf das Internet konfigurieren"));

        buttonGroup1.add(rb_directConnection);
        rb_directConnection.setSelected(true);
        rb_directConnection.setText("Direkte Verbindung zum Internet");
        rb_directConnection.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rb_directConnection.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rb_directConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_directConnectionActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_manuallySetConnectionDetails);
        rb_manuallySetConnectionDetails.setText("Manuelle Proxy-Konfiguration");
        rb_manuallySetConnectionDetails.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rb_manuallySetConnectionDetails.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rb_manuallySetConnectionDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_manuallySetConnectionDetailsActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_connectionDetection);
        rb_connectionDetection.setText("Die Proxy-Einstellungen für dieses Netzwerk automatisch erkennen");
        rb_connectionDetection.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rb_connectionDetection.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rb_connectionDetection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_connectionDetectionActionPerformed(evt);
            }
        });

        jPanel2.setEnabled(false);

        jLabel11.setText("Kein Proxy für:");
        jLabel11.setEnabled(false);

        httpProxyPort.setEnabled(false);

        httpProxyLabel.setText("HTTP-Proxy:");
        httpProxyLabel.setEnabled(false);

        jTextField11.setEnabled(false);

        httpProxyPortLabel.setText("Port:");
        httpProxyPortLabel.setEnabled(false);

        httpProxyURL.setEnabled(false);

        cb_useSameProxyForAllProtocols.setText("Für alle Protokolle diesen Proxyserver verwenden");
        cb_useSameProxyForAllProtocols.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cb_useSameProxyForAllProtocols.setEnabled(false);
        cb_useSameProxyForAllProtocols.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cb_useSameProxyForAllProtocols.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_useSameProxyForAllProtocolsItemStateChanged(evt);
            }
        });

        jLabel12.setText("Beispiel: .mozilla.org, .net.de, 127.0.0.1");
        jLabel12.setEnabled(false);

        sslProxyLabel.setText("SSL-Proxy:");
        sslProxyLabel.setEnabled(false);

        sslProxyURL.setEnabled(false);

        sslProxyPortLabel.setText("Port:");
        sslProxyPortLabel.setEnabled(false);

        sslProxyPort.setEnabled(false);

        ftpProxyPort.setEnabled(false);

        gopherProxyPort.setEnabled(false);

        socksHostPort.setEnabled(false);

        socksPortLabel.setText("Port:");
        socksPortLabel.setEnabled(false);

        ftpProxyPortLabel.setText("Port:");
        ftpProxyPortLabel.setEnabled(false);

        gopherProxyURL.setEnabled(false);

        ftpProxyURL.setEnabled(false);

        socksHostURL.setEnabled(false);

        socksHostLabel.setText("SOCKS-Host:");
        socksHostLabel.setEnabled(false);

        gopherProxyLabel.setText("Gopher-Proxy:");
        gopherProxyLabel.setEnabled(false);

        ftpProxyLabel.setText("FTP-Proxy:");
        ftpProxyLabel.setEnabled(false);

        jRadioButton4.setText("SOCKS v4");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setEnabled(false);
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton5.setSelected(true);
        jRadioButton5.setText("SOCKS v5");
        jRadioButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton5.setEnabled(false);
        jRadioButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        gopherProxyPortLabel.setText("Port:");
        gopherProxyPortLabel.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftpProxyLabel)
                    .addComponent(sslProxyLabel)
                    .addComponent(gopherProxyLabel)
                    .addComponent(socksHostLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ftpProxyURL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sslProxyURL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gopherProxyURL, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(socksHostURL, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(socksPortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(socksHostPort, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(gopherProxyPortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gopherProxyPort))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftpProxyPortLabel)
                            .addComponent(sslProxyPortLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftpProxyPort)
                            .addComponent(sslProxyPort, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sslProxyLabel)
                    .addComponent(sslProxyPortLabel)
                    .addComponent(sslProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sslProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftpProxyLabel)
                    .addComponent(ftpProxyPortLabel)
                    .addComponent(ftpProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftpProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gopherProxyLabel)
                    .addComponent(gopherProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gopherProxyPortLabel)
                    .addComponent(gopherProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socksHostLabel)
                    .addComponent(socksPortLabel)
                    .addComponent(socksHostPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(socksHostURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_useSameProxyForAllProtocols)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(httpProxyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(httpProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(httpProxyPortLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(httpProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpProxyLabel)
                    .addComponent(httpProxyURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(httpProxyPortLabel)
                    .addComponent(httpProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_useSameProxyForAllProtocols)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        buttonGroup1.add(rb_proxyConfigurationViaURL);
        rb_proxyConfigurationViaURL.setText("Automatische Proxy-Konfigurations-URL:");
        rb_proxyConfigurationViaURL.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rb_proxyConfigurationViaURL.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rb_proxyConfigurationViaURL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rb_proxyConfigurationViaURLItemStateChanged(evt);
            }
        });
        rb_proxyConfigurationViaURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_proxyConfigurationViaURLActionPerformed(evt);
            }
        });

        tf_autoProxyConfigurationURL.setEnabled(false);

        buttonReload.setMnemonic('N');
        buttonReload.setText("Neu laden");
        buttonReload.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_directConnection)
                    .addComponent(rb_manuallySetConnectionDetails)
                    .addComponent(rb_connectionDetection)
                    .addComponent(rb_proxyConfigurationViaURL)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(tf_autoProxyConfigurationURL, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReload)))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_directConnection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_connectionDetection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_manuallySetConnectionDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_proxyConfigurationViaURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_autoProxyConfigurationURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReload))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHelp)
                    .addComponent(buttonCancel)
                    .addComponent(buttonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        ProxySettings settings = ProxySettings.getInstance();
        if (settings.isProxyEnabled()) {
            settings.setProxyHost(httpProxyURL.getText());
            settings.setProxyPort(httpProxyPort.getText());
        }

        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    private void rb_directConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_directConnectionActionPerformed
        ProxySettings.getInstance().setProxyEnabled(false);

        // TODO add your handling code here:
        Component[] comp = jPanel2.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
        comp = jPanel3.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
    }//GEN-LAST:event_rb_directConnectionActionPerformed

    private void rb_manuallySetConnectionDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_manuallySetConnectionDetailsActionPerformed
        // TODO add your handling code here:

        ProxySettings.getInstance().setProxyEnabled(true);

        Component[] comp = jPanel2.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(true);
        }
        comp = jPanel3.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(true);
        }
    }//GEN-LAST:event_rb_manuallySetConnectionDetailsActionPerformed

    private void rb_connectionDetectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_connectionDetectionActionPerformed
        ProxySettings.getInstance().setProxyEnabled(false);

        // TODO add your handling code here:
        Component[] comp = jPanel2.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
        comp = jPanel3.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
    }//GEN-LAST:event_rb_connectionDetectionActionPerformed

    private void cb_useSameProxyForAllProtocolsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_useSameProxyForAllProtocolsItemStateChanged
        // TODO add your handling code here:
        String proxyURL = httpProxyURL.getText();
        String proxyPort = httpProxyPort.getText();
        ftpProxyURL.setText(proxyURL);
        ftpProxyPort.setText(proxyPort);
        gopherProxyURL.setText(proxyURL);
        gopherProxyPort.setText(proxyPort);
        socksHostURL.setText(proxyURL);
        socksHostPort.setText(proxyPort);
        sslProxyURL.setText(proxyURL);
        sslProxyPort.setText(proxyPort);
        JCheckBox box = (JCheckBox) evt.getSource();
        Component[] comp = jPanel3.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(!box.isSelected());
        }
    }//GEN-LAST:event_cb_useSameProxyForAllProtocolsItemStateChanged

    private void rb_proxyConfigurationViaURLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rb_proxyConfigurationViaURLItemStateChanged
        // TODO add your handling code here:
        JRadioButton btn = (JRadioButton) evt.getSource();
        tf_autoProxyConfigurationURL.setEnabled(btn.isSelected());
        buttonReload.setEnabled(btn.isSelected());
    }//GEN-LAST:event_rb_proxyConfigurationViaURLItemStateChanged

    private void rb_proxyConfigurationViaURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_proxyConfigurationViaURLActionPerformed
        // TODO add your handling code here:
        Component[] comp = jPanel2.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
        comp = jPanel3.getComponents();
        for (int i = 0, j = comp.length; i < j; i++) {
            comp[i].setEnabled(false);
        }
    }//GEN-LAST:event_rb_proxyConfigurationViaURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SetupProxyDialog dialog = new SetupProxyDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonOK;
    private javax.swing.JButton buttonReload;
    private javax.swing.JCheckBox cb_useSameProxyForAllProtocols;
    private javax.swing.JLabel ftpProxyLabel;
    private javax.swing.JTextField ftpProxyPort;
    private javax.swing.JLabel ftpProxyPortLabel;
    private javax.swing.JTextField ftpProxyURL;
    private javax.swing.JLabel gopherProxyLabel;
    private javax.swing.JTextField gopherProxyPort;
    private javax.swing.JLabel gopherProxyPortLabel;
    private javax.swing.JTextField gopherProxyURL;
    private javax.swing.JLabel httpProxyLabel;
    private javax.swing.JTextField httpProxyPort;
    private javax.swing.JLabel httpProxyPortLabel;
    private javax.swing.JTextField httpProxyURL;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JRadioButton rb_connectionDetection;
    private javax.swing.JRadioButton rb_directConnection;
    private javax.swing.JRadioButton rb_manuallySetConnectionDetails;
    private javax.swing.JRadioButton rb_proxyConfigurationViaURL;
    private javax.swing.JLabel socksHostLabel;
    private javax.swing.JTextField socksHostPort;
    private javax.swing.JTextField socksHostURL;
    private javax.swing.JLabel socksPortLabel;
    private javax.swing.JLabel sslProxyLabel;
    private javax.swing.JTextField sslProxyPort;
    private javax.swing.JLabel sslProxyPortLabel;
    private javax.swing.JTextField sslProxyURL;
    private javax.swing.JTextField tf_autoProxyConfigurationURL;
    // End of variables declaration//GEN-END:variables

}
